# Generated by Django 5.2.8 on 2025-11-24 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='related_habit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='reward',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration',
            field=models.PositiveIntegerField(default=120, help_text='Продолжительность в секундах', verbose_name='Время на выполнение'),
        ),
    ]
